# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0002_selectedmovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedmovie',
            name='num_of_member',
        ),
        migrations.AddField(
            model_name='selectedmovie',
            name='reviewer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
